### ISSUE TITLE
Error in code thor_proc_gethotkeydefs.prg

### ISSUE THREAD

**Issue by ugurlu2001** [VFPX/Thor#252]
## 📝 Provide detailed reproduction steps (if any)

1. … Code Replace in thor_proc_gethotkeydefs.prg
2. …
3. …

### ✔️ Expected result
* Working code replacement
	Procedure AddHotKeys
		Update  Result																			;
			Set HotKey = Nvl(HotKeyDefinitions.Descript, ''),									;
				nKeyCode = Nvl(HotKeyDefinitions.nKeyCode, 999),								;
				NShifts = Nvl(HotKeyDefinitions.NShifts, 0)										;
			From (This.cDestAlias)    As  Result												;
				Join ToolHotKeyAssignments														;
					On Result.PRGName = ToolHotKeyAssignments.PRGName ;
				Join HotKeyDefinitions															;
					On ToolHotKeyAssignments.HotKeyID = HotKeyDefinitions.Id

		Replace All														;
				HotKey	  With	Chrtran(Nvl(HotKey, ''), '-', '+')		;
				Descript  With	Strtran(Descript, '\<', '')				;
				Source	  With	Strtran(Source, '\<', '')				;
				PRGName	  With	Lower(PRGName)							;
			In (This.cDestAlias)

	Endproc
What is the expected result of the above steps?

* Error in following code 
Procedure AddHotKeys
		Update  Result																			;
			Set HotKey = Nvl(HotKeyDefinitions.Descript, ''),									;
				nKeyCode = Nvl(HotKeyDefinitions.nKeyCode, 999),								;
				NShifts = Nvl(HotKeyDefinitions.NShifts, 0)										;
			From (This.cDestAlias)    As  Result												;
				Join ToolHotKeyAssignments														;
					On Upper(Result.PRGName) = Upper(Forceext(ToolHotKeyAssignments.PRGName, 'PRG')) ;
				Join HotKeyDefinitions															;
					On ToolHotKeyAssignments.HotKeyID = HotKeyDefinitions.Id

		Replace All														;
				HotKey	  With	Chrtran(Nvl(HotKey, ''), '-', '+')		;
				Descript  With	Strtran(Descript, '\<', '')				;
				Source	  With	Strtran(Source, '\<', '')				;
				PRGName	  With	Lower(PRGName)							;
			In (This.cDestAlias)
	Endproc		

### ❌ Actual result

What is the actual result of the above steps?

## 📷 Debugging Info
Please add screenshots of
- Error Message
- Windows from the debugger
     - Trace window
     - Locals window
     - Call stack window

## 📷 Screenshots
Are there any other useful screenshots? WinKey+Shift+S and then just paste them directly into the form.

**Comment by Jimrnelson** [comment]
So this wasn't a hard error, rather a problem where it was showing inaccurate results, correct?

The way I read the original code, it would not fail on an error, it would simply work incorrectly for items that did not have a PRG extension.

Is that what you found?

**Comment by Jimrnelson** [comment]
Further question:

Have you updated to the current version of "Thor Repository" (65.18) ?  I believe this problem was resolved there.

**Comment by ugurlu2001** [comment]
Currently I shipped a new laptop and install latest version of Thor.

When run "Thor\Thor Manager" error firing and message is :: Program Error :: Invalid key length. (May be related by different code page issues (  1252 US_english, 1254 TR_Turkish )  )

After the code replacement that I send to you, everything working well on my environment. 

* Second Error related in "Thor\Launcher" : 
When select an child item and after click "Toolbar?" checkbox, everything looks like well. And later clicking another child item and firing an error :: Program Error Alias 'HOTKEYDEFINITIONS' is not found... >> Opening VFP Debugger and Trace window is focusing "ohotkeycontrols::Refresh" (probably all tables closing after trigger the checkbox -I did not deep dive to debug yet-)

Currently I updated my old laptop and run latest version of Thor. Same issue/problem continue...

**Comment by Jimrnelson** [comment]
Your suggested code modifies one line to look like this:

>  `On Result.PRGName = ToolHotKeyAssignments.PRGName ;`

However, you removed the calls to Upper(), so it should look like this:

`On Upper(Result.PRGName) = Upper(ToolHotKeyAssignments.PRGName) ;`

Will this modification work for you?

**Comment by ugurlu2001** [comment]
Yes, removed UPPER() and FORCEEXT() functions, and this modification work for me.

But the second error persists.I keep getting the second error as I explained in the title above : "Thor\Launcher"

**Comment by Jimrnelson** [comment]
Actually, the use of UPPER is necessary, so my question to you is whether this line works for you instead of your suggestion:

`On Upper(Result.PRGName) = Upper(ToolHotKeyAssignments.PRGName) ;`

There is no guarantee in either table about whether the fields are in upper, lower, or mixed case.

***

As for the second error, I am aware of it.  I hope to have it fixed in the next update to Thor.

**Comment by ugurlu2001** [comment]
I am sending this message not as a suggestion but because I am getting an error and I am sharing the screenshots with you. 

![invalid-key-length](https://github.com/VFPX/Thor/assets/8925439/238de7a6-074f-41d2-802e-cb1075fdf4a3)

![Alias HotKeyDefinitions not found](https://github.com/VFPX/Thor/assets/8925439/a48dfba5-9749-444c-8e6a-6f91de0eb3ce)

**Comment by ugurlu2001** [comment]
> Actually, the use of UPPER is necessary, so my question to you is whether this line works for you instead of your suggestion:
> 
> `On Upper(Result.PRGName) = Upper(ToolHotKeyAssignments.PRGName) ;`
> 
> There is no guarantee in either table about whether the fields are in upper, lower, or mixed case.
> 
> As for the second error, I am aware of it. I hope to have it fixed in the next update to Thor.

On Upper(Result.PRGName) = Upper(ToolHotKeyAssignments.PRGName) ;

is working well too ( ForceExt removed )

**Comment by Jimrnelson** [comment]
Corrected in Thor 1.47.02 - Released 2024-01-13 #253

**Comment by ugurlu2001** [comment]
Hello Jim,

Both bugs fixed. I update the latest version of Thor and working well.

Thank you for your great support.

With my best...
